export const REACT_QUERY_KEYS = {
  //common
  GET_MENU: "GET_MENU",
  GET_PARAMS: "GET_PARAMS",

  // users
  GET_ALL_USERS: "GET_ALL_USERS",
  // Roles
  GET_ALL_ROLES: "GET_ALL_ROLES",
  GET_ROLES_OPTION: "GET_ROLES_OPTION",

  // Object Action
  GET_OBJECT_ACTION_TREE: "GET_OBJECT_ACTION_TREE",
  GET_OBJECT_LIST: "GET_OBJECT_LIST",

  // Products
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  GET_PRODUCT_DETAIL: "GET_PRODUCT_DETAIL",
  GET_ALL_PRODUCT_ATTRIBUTES: "GET_ALL_PRODUCT_ATTRIBUTES",
  GET_DETAIL_PRODUCT_ATTRIBUTE: "GET_DETAIL_PRODUCT_ATTRIBUTE",

  // Sales Management
  SEARCH_CUSTOMERS: "SEARCH_CUSTOMERS",
  GET_ALL_ORDERS: "GET_ALL_ORDERS",
  GET_ORDER_DETAIL: "GET_ORDER_DETAIL",

  // Promotion Management
  GET_PROMOTIONS: "GET_PROMOTIONS",
  GET_PROMOTION_DETAIL: "GET_PROMOTION_DETAIL",
  GET_APPLICABLE_PRODUCTS: "GET_APPLICABLE_PRODUCTS",

  // Debt Management
  GET_ALL_DEBTS: "GET_ALL_DEBTS",
  GET_DEBT_DETAIL: "GET_DEBT_DETAIL",
};
